export const eventTable = [
    {
      selector: (row) => row?.ename, 
      name: "Event Name",
      sortField: "ename",
      sortable: true,
      minwidth: "150px",
    },
    {
      selector: (row) => row?.hname, 
      name: "Host Name",
      sortField: "hname",
      sortable: true,
      minwidth: "150px",
    },
    {
      selector: (row) => row?.eventdate, 
      name: "Event Date",
      sortField: "eventdate",
      sortable: true,
      minwidth: "150px",
    },
    {
      selector: (row) => row?.hno, 
      name: "Address 1",
      sortField: "hno",
      sortable: true,
      minwidth: "150px",
    },
    {
      selector: (row) => row?.address, 
      name: "Address 2",
      sortField: "address",
      sortable: true,
      minwidth: "150px",
    },
    {
      selector: (row) => row?.vipticket, 
      name: "VIP Ticket",
      sortField: "vipticket",
      sortable: true,
      minwidth: "100px",
    },
    {
      selector: (row) => row?.vvipticket, 
      name: "VVIP Ticket",
      sortField: "vvipticket",
      sortable: true,
      minwidth: "100px",
    },
    {
      selector: (row) => row?.goldticket, 
      name: "Gold Ticket",
      sortField: "goldticket",
      sortable: true,
      minwidth: "100px",
    },
  ];

  export const participateEventTable = [
    {
      selector: (row) => row?.ename, 
      name: "Event Name",
      sortField: "ename",
      sortable: true,
      minwidth: "150px",
    },
    {
      selector: (row) => row?.hname, 
      name: "Host Name",
      sortField: "hname",
      sortable: true,
      minwidth: "150px",
    },
    {
      selector: (row) => row?.eventdate, 
      name: "Event Date",
      sortField: "eventdate",
      sortable: true,
      minwidth: "150px",
    },
    {
      selector: (row) => row?.hno, 
      name: "Address 1",
      sortField: "hno",
      sortable: true,
      minwidth: "150px",
    },
    {
      selector: (row) => row?.address, 
      name: "Address 2",
      sortField: "address",
      sortable: true,
      minwidth: "150px",
    },
    {
      selector: (row) => row?.tickettype, 
      name: "Ticket Type",
      sortField: "tickettype",
      sortable: true,
      minwidth: "100px",
    },
    {
      selector: (row) => row?.ticketQuantity, 
      name: "Total Ticket",
      sortField: "ticketQuantity",
      sortable: true,
      minwidth: "100px",
    },
    {
      selector: (row) => row?.totalamount, 
      name: "Total Amount",
      sortField: "totalamount",
      sortable: true,
      minwidth: "100px",
    },
  ];
  export const userParticipateEventTable = [
    {
      selector: (row) => `${row?.fname || ''} ${row?.lname || ''}`.trim(), 
      name: "Name",
      sortField: "fullName",
      sortable: true,
      minwidth: "100px",
    },
    {
      selector: (row) => row?.ename, 
      name: "Event Name",
      sortField: "ename",
      sortable: true,
      minwidth: "100px",
    },
    {
      selector: (row) => row?.hname, 
      name: "Host Name",
      sortField: "hname",
      sortable: true,
      minwidth: "100px",
    },
    {
      selector: (row) => row?.eventdate, 
      name: "Event Date",
      sortField: "eventdate",
      sortable: true,
      minwidth: "100px",
    },
    {
      selector: (row) => row?.hno, 
      name: "Address 1",
      sortField: "hno",
      sortable: true,
      minwidth: "100px",
    },
    {
      selector: (row) => row?.address, 
      name: "Address 2",
      sortField: "address",
      sortable: true,
      minwidth: "100px",
    },
    {
      selector: (row) => row?.tickettype, 
      name: "Ticket Type",
      sortField: "tickettype",
      sortable: true,
      minwidth: "100px",
    },
    {
      selector: (row) => row?.ticketQuantity, 
      name: "Total Ticket",
      sortField: "ticketQuantity",
      sortable: true,
      minwidth: "100px",
    },
    {
      selector: (row) => row?.totalamount, 
      name: "Total Amount",
      sortField: "totalamount",
      sortable: true,
      minwidth: "100px",
    },
  ];
  
  export const userTable=[
    {
        selector:(row)=>row?.fname,
        name:"First Name",
        sortField:"fname",
        sortable:true,
        minwidth:"150px",
    },
    {
        selector:(row)=>row?.lname,
        name:"Last Name",
        sortField:"lname",
        sortable:true,
        minwidth:"150px",
    },
    {
        selector:(row)=>row?.email,
        name:"Email",
        sortField:"email",
        sortable:true,
        minwidth:"150px",
    },
    {
        selector:(row)=>row?.age,
        name:"Age",
        sortField:"age",
        sortable:true,
        minwidth:"150px",
    },
    {
        selector:(row)=>row?.dob,
        name:"Birth Date",
        sortField:"dob",
        sortable:true,
        minwidth:"150px",
    },
    {
        selector:(row)=>row?.role,
        name:"Role",
        sortField:"role",
        sortable:true,
        minwidth:"150px",
    }
  ]